# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/spok/q

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/spok/q

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spok/q/CMakeFiles /home/spok/q/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/spok/q/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game

# Build rule for target.
game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 game
.PHONY : game

# fast build rule for target.
game/fast:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/build
.PHONY : game/fast

src/engine/client/graphics.o: src/engine/client/graphics.cpp.o
.PHONY : src/engine/client/graphics.o

# target to build an object file
src/engine/client/graphics.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/client/graphics.cpp.o
.PHONY : src/engine/client/graphics.cpp.o

src/engine/client/graphics.i: src/engine/client/graphics.cpp.i
.PHONY : src/engine/client/graphics.i

# target to preprocess a source file
src/engine/client/graphics.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/client/graphics.cpp.i
.PHONY : src/engine/client/graphics.cpp.i

src/engine/client/graphics.s: src/engine/client/graphics.cpp.s
.PHONY : src/engine/client/graphics.s

# target to generate assembly for a file
src/engine/client/graphics.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/client/graphics.cpp.s
.PHONY : src/engine/client/graphics.cpp.s

src/engine/client/main.o: src/engine/client/main.cpp.o
.PHONY : src/engine/client/main.o

# target to build an object file
src/engine/client/main.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/client/main.cpp.o
.PHONY : src/engine/client/main.cpp.o

src/engine/client/main.i: src/engine/client/main.cpp.i
.PHONY : src/engine/client/main.i

# target to preprocess a source file
src/engine/client/main.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/client/main.cpp.i
.PHONY : src/engine/client/main.cpp.i

src/engine/client/main.s: src/engine/client/main.cpp.s
.PHONY : src/engine/client/main.s

# target to generate assembly for a file
src/engine/client/main.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/client/main.cpp.s
.PHONY : src/engine/client/main.cpp.s

src/engine/client/textrender.o: src/engine/client/textrender.cpp.o
.PHONY : src/engine/client/textrender.o

# target to build an object file
src/engine/client/textrender.cpp.o:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/client/textrender.cpp.o
.PHONY : src/engine/client/textrender.cpp.o

src/engine/client/textrender.i: src/engine/client/textrender.cpp.i
.PHONY : src/engine/client/textrender.i

# target to preprocess a source file
src/engine/client/textrender.cpp.i:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/client/textrender.cpp.i
.PHONY : src/engine/client/textrender.cpp.i

src/engine/client/textrender.s: src/engine/client/textrender.cpp.s
.PHONY : src/engine/client/textrender.s

# target to generate assembly for a file
src/engine/client/textrender.cpp.s:
	$(MAKE) -f CMakeFiles/game.dir/build.make CMakeFiles/game.dir/src/engine/client/textrender.cpp.s
.PHONY : src/engine/client/textrender.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... game"
	@echo "... rebuild_cache"
	@echo "... src/engine/client/graphics.o"
	@echo "... src/engine/client/graphics.i"
	@echo "... src/engine/client/graphics.s"
	@echo "... src/engine/client/main.o"
	@echo "... src/engine/client/main.i"
	@echo "... src/engine/client/main.s"
	@echo "... src/engine/client/textrender.o"
	@echo "... src/engine/client/textrender.i"
	@echo "... src/engine/client/textrender.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

